In [12]:
import pandas as pd

path = r"D:\progs\fuzzy-chainsaw\2024_2025\EclBin\data_5\LC.txt"

In [13]:
df = pd.read_csv(path, sep='\s+')
df

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ryzho\AppData\Local\Temp\ipykernel_8132\577356795.py:1: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(path, sep='\s+')

              HJD    Phase  Vdmag
0     51862.52954  0.20706 -0.355
1     51862.53070  0.20727 -0.355
2     51862.53186  0.20749 -0.350
3     51862.53301  0.20769 -0.360
4     51862.53418  0.20791 -0.357
...           ...      ...    ...
6445  52890.96459  0.00941  0.085
6446  52890.96555  0.00958  0.067
6447  52890.96652  0.00976  0.085
6448  52890.96748  0.00994  0.043
6449  52890.96844  0.01011  0.039

[6450 rows x 3 columns]

In [14]:
dict_new = {
    'data' : df['HJD'],
    'mag' : df['Vdmag'] + 9.555
}

df_new = pd.DataFrame.from_dict(dict_new)

df_new

             data    mag
0     51862.52954  9.200
1     51862.53070  9.200
2     51862.53186  9.205
3     51862.53301  9.195
4     51862.53418  9.198
...           ...    ...
6445  52890.96459  9.640
6446  52890.96555  9.622
6447  52890.96652  9.640
6448  52890.96748  9.598
6449  52890.96844  9.594

[6450 rows x 2 columns]

In [15]:
df_new.to_csv('LC_new.csv', index=False)